name: Deploy Next.js to FTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 25

      # 🔥 Install deps
      - name: Install deps
        run: npm install

      # 🔥 Build
      - name: Build
        run: npm run build
        env:
          NEXT_PUBLIC_BACKEND_URL: ${{ secrets.ENV_NEXT_PUBLIC_BACKEND_URL }}
          NEXT_PUBLIC_BACKEND_API_PATH: ${{ secrets.ENV_NEXT_PUBLIC_BACKEND_API_PATH }}

      # 🔥 Install production deps only
      - name: Install production deps only
        run: |
          rm -rf node_modules
          npm install --omit=dev

      # 🔥 Prepare folder + zip
      - name: Zip project
        run: |
          mkdir deploy
          zip -r deploy/deploy.zip . \
            -x "deploy/*" \
            -x "*.git*" \
            -x "node_modules/.cache/*" \
            -x ".next/cache/*"

      # 🔥 Upload
      - name: Upload ZIP via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: deploy/
          server-dir: /
          dangerous-clean-slate: false